//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppBase.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppBaseEntities : DbContext
    {
        public AppBaseEntities()
            : base("name=AppBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Function> Functions { get; set; }
        public virtual DbSet<Right> Rights { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<TabRowDetail> TabRowDetails { get; set; }
        public virtual DbSet<TabRow> TabRows { get; set; }
        public virtual DbSet<Tab> Tabs { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
