//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppBase.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Right
    {
        public string RoleName { get; set; }
        public string FunctionName { get; set; }
        public bool IsEnabled { get; set; }
    
        public virtual Function Function { get; set; }
        public virtual Role Role { get; set; }
    }
}
