//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppBase.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabRow
    {
        public string CodTab { get; set; }
        public string Cod { get; set; }
        public string Description { get; set; }
    
        public virtual TabRowDetail TabRowDetail { get; set; }
        public virtual TabRowDetail TabRowDetail1 { get; set; }
        public virtual Tab Tab { get; set; }
    }
}
