//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppBase.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabRowDetail
    {
        public string CodTab { get; set; }
        public string Cod { get; set; }
        public Nullable<int> Pos { get; set; }
        public string ExtraInfo { get; set; }
    
        public virtual TabRow TabRow { get; set; }
        public virtual TabRow TabRow1 { get; set; }
    }
}
